DomClickCRM/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include
from tickets.views import WelcomePageView, SignUpView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', WelcomePageView.as_view(), name='welcome_page'),
    path('tickets/', include('tickets.urls', namespace='tickets')),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('employees/', include('employees.urls', namespace='employees'))
]

if settings.DEBUG:
    urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tickets/urls.py
from django.urls import path
from .views import TicketListView, TicketDetailView, TicketCreateView, TicketUpdateView, TicketDeleteView

app_name = 'tickets'

urlpatterns = [
    path('', TicketListView.as_view(), name='all-tickets'),
    path('<int:pk>/', TicketDetailView.as_view(), name='ticket_details'),
    path('<int:pk>/update/', TicketUpdateView.as_view(), name='ticket_update'),
    path('<int:pk>/delete/', TicketDeleteView.as_view(), name='ticket_delete'),
    path('create/', TicketCreateView.as_view(), name='ticket_create')
]

tickets/models.py
from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    is_manager = models.BooleanField(default=True)
    is_supermanager = models.BooleanField(default=False)


class ProfileModel(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='userprofile')

    def __str__(self):
        return self.user.username


class Ticket(models.Model):
    name = models.CharField(max_length=256)
    date = models.DateTimeField(auto_now_add=True, blank=True)
    details = models.CharField(max_length=1000)
    urgent = models.BooleanField(default=False)
    company = models.ForeignKey(ProfileModel,null=True, blank=True, on_delete=models.CASCADE)
    employee = models.ForeignKey("Employee", null=True, blank=True, on_delete=models.SET_NULL)
    category = models.ForeignKey("Category",null=True, blank=True, on_delete=models.SET_NULL)
    status = models.ForeignKey("Status", null=True, blank=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.name


class Employee(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    company = models.ForeignKey(ProfileModel, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.email


class Category(models.Model):
    name = models.CharField(max_length=25)

    def __str__(self):
        return self.name


class Status(models.Model):
    name = models.CharField(max_length=25)

    def __str__(self):
        return self.name


def post_user_signal(sender, instance, created, **kwargs):
    if created:
        ProfileModel.objects.create(user=instance)


post_save.connect(post_user_signal, sender=User)

tickets/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UsernameField
from .models import Ticket

User = get_user_model()


class TicketForm(forms.ModelForm):

    class Meta:
        model = Ticket
        fields = (
            'name',
            'details',
            'category',
            'urgent',
            'employee',
            'status'
        )


class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username",)
        field_classes = {'username': UsernameField}

tickets/views.py
from django.shortcuts import reverse
from django.core.mail import send_mail
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Ticket, Employee
from .forms import TicketForm, UserRegisterForm
from .filters import TicketFilter
from .bot import send_msg


class SignUpView(CreateView):
    template_name = "registration/sign_up.html"
    form_class = UserRegisterForm

    def get_success_url(self):
        return reverse('login')


class WelcomePageView(TemplateView):
    template_name = 'welcome_page.html'


class TicketListView(LoginRequiredMixin, ListView):
    model = Ticket
    template_name = 'tickets/ticket_list.html'
    context_object_name = 'tickets'

    def get_queryset(self):
        if self.request.user.is_manager:
            queryset = Ticket.objects.filter(employee__isnull=False)
        else:
            queryset = Ticket.objects.filter(company=self.request.user.employee.company)
        queryset = queryset.filter(employee__user=self.request.user)
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(TicketListView, self).get_context_data(**kwargs)
        if self.request.user.is_manager:
            querysetAssigned = Ticket.objects.filter(employee__isnull=False)
            querysetUnassigned = Ticket.objects.filter(employee__isnull=True)
            context['tickets'] = TicketFilter(self.request.GET, queryset=querysetAssigned)
            context['filter'] = TicketFilter(self.request.GET, queryset=querysetUnassigned)
            context.update({
                "unassigned_tickets" : self.get_queryset()
            })
        return context


class TicketDetailView(LoginRequiredMixin, DetailView):
    template_name = 'tickets/ticket_detail.html'
    queryset = Ticket.objects.all()
    context_object_name = 'ticket'


class TicketCreateView(LoginRequiredMixin, CreateView):
    template_name = 'tickets/ticket_create.html'
    form_class = TicketForm

    def get_success_url(self):
        return reverse('tickets:all-tickets')

    def form_valid(self, form):
        send_mail(
            subject="New ticket has been created and assigned to an employee.",
            message="Review new ticket at ##",
            from_email="test@testdomclick.ru",
            recipient_list=["employee@testdomclick.ru"]
         )
        return super(TicketCreateView, self).form_valid(form)


class TicketUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'tickets/ticket_update.html'
    queryset = Ticket.objects.all()
    form_class = TicketForm

    def get_success_url(self):
        emp = self.request.POST['employee']
        if self.request.POST['status'] == "1":
            send_msg(f"{self.request.POST['name']} status has been changed to OPEN. "
                     f"Employee - {Employee.objects.get(id=emp)}")
        elif self.request.POST['status'] == "2":
            send_msg(f"{self.request.POST['name']} status has been changed to CLOSED."
                     f"Employee - {Employee.objects.get(id=emp)}")
        elif self.request.POST['status'] == "3":
            send_msg(f"{self.request.POST['name']} status has been changed to PAUSED. "
                     f"Employee - {Employee.objects.get(id=emp)}")
        return reverse('tickets:all-tickets')


class TicketDeleteView(DeleteView):
    template_name = 'tickets/ticket_delete.html'
    queryset = Ticket.objects.all()
    form_class = TicketForm

    def get_success_url(self):
        return reverse('tickets:all-tickets')

tickets/templates/tickets/ticket_create.html
{% extends 'base.html' %}
{% block content %}
<a href="{% url 'tickets:all-tickets' %}">Go back to all tickets</a>
<hr />
<h1>Create a new ticket</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit </button>
</form>
{% endblock content %}

tickets/templates/tickets/ticket_delete.html
{% extends 'base.html' %}
{% block content %}
<a href="{% url 'tickets:all-tickets' %}">Go back to all tickets</a>
<hr />
<h1>Delete the ticket?</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit </button>
</form>
{% endblock content %}

tickets/templates/tickets/ticket_detail.html
{% extends 'base.html' %}
{% block content %}
<a href="{% url 'tickets:all-tickets' %}">Go back to all tickets</a>
<hr />
<h1>Detailed view of the ticked called {{ ticket.name }}</h1>
    <p>{{ ticket.employee }} - {{ ticket.details }}</p>
    <p>Ticket assigned for {{ ticket.employee }}</p>
    <p>Details - {{ ticket.details }}</p>
<hr />
<a href="{% url 'tickets:ticket_update' ticket.pk %}">UPDATE</a>
<a href="{% url 'tickets:ticket_delete' ticket.pk %}">DELETE</a>
{% endblock content %}

tickets/templates/tickets/ticket_list.html
{% extends 'base.html' %}
{% block content %}
    {% if request.user.is_supermanager %}
<a href="{% url 'tickets:ticket_create' %}">
    <button type="button" class="btn btn-primary">New Ticket</button>
</a>

    {% endif %}
    <form method="get">
        {{ filter.form }}
    <button type="submit">Search</button>
    </form>
<hr/>

{% for ticket in tickets.qs %}
    <div class="ticket">
            <b>Ticket name</b> - {{ ticket.name }} </a>
            <b>Employee</b> - {{ ticket.employee }}
            <b>Ugrent</b> - {{ ticket.urgent }}
            <b>Category</b> - {{ ticket.category }}
            <b>Date</b> - {{ ticket.date }}
            <b>Status:</b> - {{ ticket.status }}
        <a href="{% url 'tickets:ticket_details' ticket.pk %}">Details</a>
    </div>
{% endfor %}
    <br>
{% if unassigned_tickets.exists %}
    <h2>Unassigned tickets</h2>
    {% for ticket in filter.qs %}
        <div class="ticket">
           <a href="{% url 'tickets:ticket_details' ticket.pk %}">
               <b>Ticket name</b>  - {{ ticket.name }} </a>
                <b>Ugrent </b> - {{ ticket.urgent }}
                <b>Category</b> - {{ ticket.category }}
                <b>Date</b> - {{ ticket.date }}
                <b>Status</b> - {{ ticket.status }}
                <a href="{% url 'tickets:ticket_details' ticket.pk %}">Details</a>
        </div>
    {% endfor %}
{% endif %}
{% endblock content %}

tickets/templates/tickets/ticket_update.html
{% extends 'base.html' %}
{% block content %}
<a href="{% url 'tickets:ticket_details' ticket.pk %}">Go back to {{ ticket.name }}</a>
<hr />
<h1>Update ticket: {{ ticket.name }}</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
</form>
{% endblock content %}