DomClickCRM/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include
from tickets.views import WelcomePageView, SignUpView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', WelcomePageView.as_view(), name='welcome_page'),
    path('tickets/', include('tickets.urls', namespace='tickets')),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('employees/', include('employees.urls', namespace='employees'))
]

if settings.DEBUG:
    urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

employees/urls.py
from django.urls import path
from .views import EmployeeView, EmployeeCreateView, EmployeeDetail, EmployeeUpdate, EmployeeTickets

app_name = "employees"

urlpatterns = [
    path('', EmployeeView.as_view(), name='employees'),
    path('create/', EmployeeCreateView.as_view(), name='employee-create'),
    path('<int:pk>/', EmployeeDetail.as_view(), name='employee_detail'),
    path('<int:pk>/update/', EmployeeUpdate.as_view(), name='employee_update'),
    path('mytickets/', EmployeeTickets.as_view(), name='employee_tickets')
]

tickets/urls.py
from django.urls import path
from .views import TicketListView, TicketDetailView, TicketCreateView, TicketUpdateView, TicketDeleteView

app_name = 'tickets'

urlpatterns = [
    path('', TicketListView.as_view(), name='all-tickets'),
    path('<int:pk>/', TicketDetailView.as_view(), name='ticket_details'),
    path('<int:pk>/update/', TicketUpdateView.as_view(), name='ticket_update'),
    path('<int:pk>/delete/', TicketDeleteView.as_view(), name='ticket_delete'),
    path('create/', TicketCreateView.as_view(), name='ticket_create')
]

templates/base.html
{% load static  %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>DomClick CRM</title>
    <link href="{% static "static/css/styles.css" %}" rel="stylesheet"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">DomClick CRM</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'tickets:all-tickets' %}">All tickets</a>
        </li>
          <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'employees:employee_tickets' %}">My tickets</a>
        </li>
        {% if not request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'signup' %}">Sign Up</a>
        </li>
        {% endif %}
          {% if request.user.is_authenticated %}
              <li class="nav-item">
              {% if request.user.is_supermanager %}
              <a class="nav-link" href="{% url 'employees:employees' %}">Employee list</a>
              </li>
                  {% endif %}
              <li class="nav-item">
                <a class="nav-link" href="#">Logged in as: {{ request.user.username }}</a>
              </li>
              <li class="nav-item">
              <a class="nav-link" href="{% url 'logout' %}">Logout</a>
              </li>
          {% else %}
             <li class="nav-item">
               <a class="nav-link" href="{% url 'login' %}">Login</a>
             </li>
          {% endif %}
      </ul>
    </div>
  </div>
</nav>
<div class="container">
    <div class="col-md-10 offset-md-1 mt-5">
        <div class="jumbotron">
            <h1><div class="text-center">DomClick CRM</div></h1>
          <hr class="my-4">
            {% block content %}
            {% endblock content %}
        </div>
    </div>
</div>


<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
</body>
</html>

templates/welcome_page.html
{% load static  %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>DomClick CRM</title>
    <link href="{% static "static/css/styles.css" %}" rel="stylesheet"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>

    <div class="card text-center" style="width: 18rem; margin-top: 250px; margin-left: 540px">
      <img src="static/domclick-logo.svg" class="card-img-top" alt="...">
      <div class="card-body text-center">
        <h5 class="card-title"> DomClick CRM</h5>
        <p class="card-text">Start managing tickets!</p>
          <div class="col text-center">
              <a href="{% url "login" %}" class="btn btn-primary ">Login</a>
              OR
              <a href="{% url "signup" %}" class="btn btn-primary ">SignUp</a>
              <br>
              If you're already logged in click - <a href="{% url "tickets:all-tickets" %}" class="btn btn-primary ">HERE</a>
          </div>

      </div>
    </div>


<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
</body>
</html>