DomClickCRM/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include
from tickets.views import WelcomePageView, SignUpView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', WelcomePageView.as_view(), name='welcome_page'),
    path('tickets/', include('tickets.urls', namespace='tickets')),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('employees/', include('employees.urls', namespace='employees'))
]

if settings.DEBUG:
    urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

employees/urls.py
from django.urls import path
from .views import EmployeeView, EmployeeCreateView, EmployeeDetail, EmployeeUpdate, EmployeeTickets

app_name = "employees"

urlpatterns = [
    path('', EmployeeView.as_view(), name='employees'),
    path('create/', EmployeeCreateView.as_view(), name='employee-create'),
    path('<int:pk>/', EmployeeDetail.as_view(), name='employee_detail'),
    path('<int:pk>/update/', EmployeeUpdate.as_view(), name='employee_update'),
    path('mytickets/', EmployeeTickets.as_view(), name='employee_tickets')
]

tickets/urls.py
from django.urls import path
from .views import TicketListView, TicketDetailView, TicketCreateView, TicketUpdateView, TicketDeleteView

app_name = 'tickets'

urlpatterns = [
    path('', TicketListView.as_view(), name='all-tickets'),
    path('<int:pk>/', TicketDetailView.as_view(), name='ticket_details'),
    path('<int:pk>/update/', TicketUpdateView.as_view(), name='ticket_update'),
    path('<int:pk>/delete/', TicketDeleteView.as_view(), name='ticket_delete'),
    path('create/', TicketCreateView.as_view(), name='ticket_create')
]

employees/models.py
from django.db import models

# Create your models here.

employees/forms.py
from django import forms
from tickets.models import Employee


class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = ('user',)

employees/views.py
from django.views import generic
from django.shortcuts import reverse
from django.contrib.auth.decorators import login_required
from tickets.models import Employee
from .forms import EmployeeForm
from .mixins import ManagerAndLoginReqMixin
from tickets.models import Ticket


class EmployeeView(ManagerAndLoginReqMixin, generic.ListView):
    template_name = "employees/employee_list.html"

    def get_queryset(self):
        company = self.request.user.employee.company
        return Employee.objects.all()


class EmployeeCreateView(ManagerAndLoginReqMixin, generic.CreateView):
    template_name = "employees/employee_create.html"
    form_class = EmployeeForm

    def get_success_url(self):
        return reverse("employees:employees")

    def form_valid(self, form):
        employee = form.save(commit=False)
        employee.company = self.request.user.userprofile
        employee.save()
        return super(EmployeeCreateView, self).form_valid(form)


class EmployeeDetail(ManagerAndLoginReqMixin, generic.DetailView):
    template_name = 'employees/employee_detail.html'
    context_object_name = 'employee'

    def get_queryset(self):
        company = self.request.user.userprofile
        return Employee.objects.filter(company=company)


class EmployeeTickets(ManagerAndLoginReqMixin, generic.ListView):
    template_name = "employees/employee_tickets.html"
    model = Ticket
    context_object_name = 'emtickets'

    def get_queryset(self):
        return Ticket.objects.filter(employee__user=self.request.user)


class EmployeeUpdate(ManagerAndLoginReqMixin, generic.UpdateView):
    template_name = "employees/employee_update.html"
    form_class = EmployeeForm

    def get_success_url(self):
        return reverse("employees:employees")

    def get_queryset(self):
        company = self.request.user.userprofile
        return Employee.objects.filter(company=company)

employees/templates/employees/employee_create.html
{% extends 'base.html' %}
{% block content %}
    <a href="{% url 'employees:employees' %}">Go back to all employees</a>
    <hr />
    <h1>Create a new employee</h1>
    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit </button>
{% endblock content %}

employees/templates/employees/employee_detail.html
{% extends 'base.html' %}
{% block content %}
<a href="{% url 'employees:employees' %}">Go back to all employees</a>
<hr />
<h1>Detailed view of the employee {{  employee.user.username }}</h1>
<hr />
    <h1>My tickets</h1>

<a href="{% url 'employees:employee_update' employee.pk %}">UPDATE</a>
{% endblock content %}

employees/templates/employees/employee_list.html
{% extends 'base.html' %}
{% block content %}
    <a href="{% url "employees:employee-create" %}">Create a new employee</a>
    <hr />
<h1>All employees</h1>
    {% for employee in object_list %}
        <p><a href="{% url 'employees:employee_detail' employee.pk %}">{{ employee }}</a> </p>
    {% endfor %}
{% endblock content %}

employees/templates/employees/employee_tickets.html
{% extends 'base.html' %}
{% block content %}
<h1>My tickets</h1>
    {% for ticket in emtickets %}
        <a href="{% url 'tickets:ticket_details' ticket.pk %}"><p>{{ ticket }}</p></a>
    {% endfor %}
{% endblock content %}

employees/templates/employees/employee_update.html
{% extends 'base.html' %}
{% block content %}
<a href="{% url 'employees:employee_detail' employee.pk %}">Go back to {{ user.username }}</a>
<hr />
<h1>Update Employee: {{ employee.name }}</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
</form>
{% endblock content %}